# wrangler.toml
name = "warren-ai-daily"
main = "src/index.js" # <-- Important: path to your main worker script
compatibility_date = "2025-05-20" # Or your project's compatibility date
workers_dev = true

kv_namespaces = [
  { binding = "DATA_KV", id = "bf3f91e7cb7b4b1b87cd0606f867de3a" }
]

[vars]
IMG_PROXY = ""  #图片代理链接，用于处理图片不显示
OPEN_TRANSLATE = "true"
USE_MODEL_PLATFORM = "OPEN" #GEMINI, OPEN
GEMINI_API_KEY = "替换为您的GEMINI_API_KEY"
GEMINI_API_URL = "https://api-proxy.me/gemini" #网上公共的代理api
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash-preview-05-20"
OPENAI_API_KEY = "sk-e054844de49449dc98d98d03320b4cfa" # Replace with your actual OpenAI API Key
OPENAI_API_URL = "https://api.deepseek.com" # Or your OpenAI compatible API URL
DEFAULT_OPEN_MODEL = "deepseek-reasoner"
FOLO_COOKIE_KV_KEY = "__Secure-better-auth.session_token=WH15Mk04nqivI2uiIyiBJOqLdGSLaJoy.GxJYCB7WnqmOJIGJh1cDGuMFOzWRcZF%2Be0XBwnUbsME%3D" 
FOLO_DATA_API = "https://api.follow.is/entries"
FOLO_FILTER_DAYS = 3
AIBASE_FEED_ID = "69533603812632576" 
AIBASE_FETCH_PAGES = "3" 
XIAOHU_FEED_ID = "151846580097413120" 
XIAOHU_FETCH_PAGES = "2" 
HGPAPERS_FEED_ID = "41359648680482832" 
HGPAPERS_FETCH_PAGES = "2" 
JIQIZHIXIN_FEED_ID = "41459996870678583" 
JIQIZHIXIN_FETCH_PAGES = "1" 
QBIT_FEED_ID = "58864180026527744" 
QBIT_FETCH_PAGES = "1" 
XINZHIYUAN_FEED_ID = "60901577013168128" 
XINZHIYUAN_FETCH_PAGES = "1" 
TWITTER_LIST_ID = "153028784690326528" 
TWITTER_FETCH_PAGES = "5" 
PROJECTS_API_URL = "https://git-trending.justlikemaki.vip/topone/?since=daily"
GITHUB_TOKEN = "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"
GITHUB_REPO_OWNER = "WarrenHao"
GITHUB_REPO_NAME = "AiDaily"
GITHUB_BRANCH = "main"
LOGIN_USERNAME = "root"
LOGIN_PASSWORD = "1234"
DAILY_TITLE = "AI洞察日报"
DAILY_TITLE_MIN = " `AI 日报` "
PODCAST_TITLE = "来生小酒馆"
PODCAST_BEGIN = "嘿，亲爱的V，欢迎收听新一期的来生情报站，我是你们的老朋友，何夕2077"
PODCAST_END = "今天的情报就到这里，注意隐蔽，赶紧撤离"
BOOK_LINK = ""
INSERT_FOOT = "false"